# Prometheus Configuration for Voice AI Agent - Hetzner VPS Optimized
# Lightweight monitoring configuration

global:
  scrape_interval: 30s
  evaluation_interval: 30s
  scrape_timeout: 10s
  external_labels:
    cluster: 'voice-ai-hetzner'
    environment: 'production'

# Rule files
rule_files:
  - "rules/*.yml"

# Alerting configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets: []

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 60s
    metrics_path: /metrics

  # Node Exporter (system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node_exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Voice AI API
  - job_name: 'voiceai-api'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # NGINX
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status
    
  # Ollama LLM Service
  - job_name: 'ollama'
    static_configs:
      - targets: ['ollama:11434']
    scrape_interval: 60s
    metrics_path: /metrics

  # Celery Worker
  - job_name: 'celery-worker'
    static_configs:
      - targets: ['celery_worker:8000']
    scrape_interval: 30s
    metrics_path: /metrics

# Storage configuration optimized for Hetzner VPS
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true

# Memory optimization for VPS
# Limit memory usage
runtime:
  gogc: 75