id: default
name: "Legal Consultation Default Flow"
version: "1.0"
description: "Basic flow for legal consultation intake"

start_node: greeting

nodes:
  greeting:
    type: message
    name: "Greeting"
    message: "Hello! I'm your AI legal assistant. How can I help you today?"
    next_node: intent_classification
    
  intent_classification:
    type: condition
    name: "Intent Classification"
    conditions:
      - condition: "intent == 'legal_consultation'"
        next_node: legal_consultation_node
      - condition: "intent == 'appointment_booking'"
        next_node: appointment_booking_node
    default_node: general_inquiry_node
    
  legal_consultation_node:
    type: message
    name: "Legal Consultation"
    message: "I understand you need legal consultation. Can you briefly describe your legal matter?"
    next_node: collect_details
    
  appointment_booking_node:
    type: message
    name: "Appointment Booking"
    message: "I'd be happy to help you schedule an appointment. What type of legal service do you need?"
    next_node: collect_appointment_details
    
  general_inquiry_node:
    type: message
    name: "General Inquiry"
    message: "I'm here to help with legal matters. Could you please be more specific about what you need assistance with?"
    next_node: intent_classification
    
  collect_details:
    type: slot_fill
    name: "Collect Case Details"
    slot:
      name: case_type
      type: text
      prompt: "What type of legal case is this? (e.g., personal injury, contract dispute, family law)"
      required: true
    next_node: collect_urgency
    
  collect_urgency:
    type: slot_fill
    name: "Collect Urgency"
    slot:
      name: urgency
      type: text
      prompt: "How urgent is this matter? (e.g., immediate, within a week, no rush)"
      required: false
    next_node: summary
    
  collect_appointment_details:
    type: slot_fill
    name: "Collect Preferred Date"
    slot:
      name: preferred_date
      type: text
      prompt: "What date would work best for you?"
      required: true
    next_node: collect_time
    
  collect_time:
    type: slot_fill
    name: "Collect Preferred Time"
    slot:
      name: preferred_time
      type: text
      prompt: "What time of day would you prefer? (morning, afternoon, or evening)"
      required: true
    next_node: appointment_confirmation
    
  summary:
    type: message
    name: "Summary"
    message: "Thank you for the information. I'll connect you with the appropriate legal specialist. Is there anything else I can help you with?"
    next_node: check_continue
    
  appointment_confirmation:
    type: message
    name: "Appointment Confirmation"
    message: "Perfect! I'll schedule your appointment and send you a confirmation. Is there anything else I can help you with today?"
    next_node: check_continue
    
  check_continue:
    type: condition
    name: "Check Continue"
    conditions:
      - condition: "user_wants_more_help"
        next_node: intent_classification
    default_node: end
    
  end:
    type: end
    name: "End"
    message: "Thank you for contacting us. Have a great day!"